export const FETCH_ALL_BOOKS = 'FETCH_ALL_BOOKS'
export const CHANGE_BOOK_SHELF = 'CHANGE_BOOK_SHELF'
export const SEARCH_BOOKS = 'SEARCH_BOOKS'
export const CLEAR_SEARCH_RESULT = 'CLEAR_SEARCH_RESULT'
